version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: jk_database
      POSTGRES_USER: jk_project
      POSTGRES_PASSWORD: "12"
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: jk_database
      DB_USER: jk_project
      DB_PASSWORD: "12"
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
