# Generated by Django 5.2.1 on 2025-05-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
